name: "Manually publish snapshot package"

on:
  workflow_dispatch:

jobs:
  tn-snapshot:
    name: "Publish snapshot package"
    runs-on: ubuntu-latest
    if: contains('refs/heads/staging refs/heads/main', github.ref)
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: build
        run: |
          npm run build
          
      - name: "Setup registry"
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: "Publish NPM snapshot"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNAPSHOT_VERSION: ${{ uppercase(github.ref) }}
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          NEW_VERSION="SNAPSHOT-%{SNAPSHOT_VERSION}"
          sed -i '' "s/${CURRENT_VERSION}/${NEW_VERSION}/" package.json
          npm publish --tag SNAPSHOT
