name: "tn-p1"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      attestation_ver:
        description: "Specific org.tokenscript:attestation version"
        required: false
        type: string
      use_github_packages:
        description: "Whether to use github packages for building"
        required: false
        default: false
        type: boolean

jobs:
  tn-p1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: install dependencies
        run: |
          npm ci
          if [ "${USE_GITHUB_PACKAGES}" = "true" ]; then
            echo "//npm.pkg.github.com/:_authToken=${GPR_KEY}" >> .npmrc
            echo "@tokenscript:registry=https://npm.pkg.github.com" >> .npmrc
            cat .npmrc
          fi
          if [ -n "${ATTESTATION_VER}" ]; then
            npm i -E "@tokenscript/attestation@${ATTESTATION_VER}"
            cat package.json
          fi
        env:
          ATTESTATION_VER: ${{ inputs.attestation_ver }}
          USE_GITHUB_PACKAGES: ${{ inputs.use_github_packages }}
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_KEY: ${{ secrets.GPR_KEY }}
      - name: build
        run: |
          npm run build
          npm run build-umd
      - name: test
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run test
      - uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: reports/
