name: "Manually publish snapshot package"

on:
  workflow_dispatch:

jobs:
  tn-snapshot:
    name: "Publish snapshot package"
    runs-on: ubuntu-latest
    if: contains('refs/heads/staging refs/heads/main', github.ref)
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: install dependencies
        run: |
          npm ci

      - name: build
        run: |
          npm run build

      - name: "Setup registry"
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - uses: actions/delete-package-versions@v4
        with:
          package-name: token-negotiator
          package-type: npm
          num-old-versions-to-delete: 5
          min-versions-to-keep: 5

      - name: "Publish NPM snapshot"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNAPSHOT_VERSION: ${{ github.ref == 'refs/heads/staging' && 'staging' || 'main' }}
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          SNAP_TAG="SNAPSHOT-$SNAPSHOT_VERSION"
          ./scripts/set_version.js "$CURRENT_VERSION-$SNAP_TAG.${GITHUB_SHA::6}"
          npm publish --tag "$SNAP_TAG" --ignore-prepublish
