name: "Manually publish snapshot package"

on:
  workflow_dispatch:

jobs:
  tn-snapshot:
    name: "Publish snapshot package"
    runs-on: ubuntu-latest
    if: contains('refs/heads/staging refs/heads/main', github.ref)
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: install dependencies
        run: |
          npm ci
          # make SNAPSHOT-staging package to use @tokenscript/attestation:SNAPSHOT-staging
          if [ "${GITHUB_REF_NAME}" = "staging" ]; then
            echo "//npm.pkg.github.com/:_authToken=${GPR_KEY}" >> .npmrc
            echo "@tokenscript:registry=https://npm.pkg.github.com" >> .npmrc
            npm i "@tokenscript/attestation@SNAPSHOT-staging"
          fi
        env:
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: |
          npm run build

      - name: "Setup registry"
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"

      - name: "Publish NPM snapshot"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNAPSHOT_VERSION: ${{ github.ref == 'refs/heads/staging' && 'staging' || 'main' }}
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          SNAP_TAG="SNAPSHOT-$SNAPSHOT_VERSION"
          ./scripts/set_version.js "$CURRENT_VERSION-$SNAP_TAG.${GITHUB_SHA::6}"
          npm publish --tag "$SNAP_TAG" --access restricted

      - uses: actions/delete-package-versions@v4
        with:
          package-name: token-negotiator
          package-type: npm
          min-versions-to-keep: 4
          delete-only-pre-release-versions: "true"
