name: "Token Negotiator CI"

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - "*"

jobs:
  tn-p1:
    uses: ./.github/workflows/tn-p1.yml

  sonarcloud:
    needs:
      - tn-p1
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/download-artifact@v3
        with:
          name: test-report
          path: reports/
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
